package newpackage;

/**
 *
 * @author Optiplex
 */
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
public class NewJFrame11 extends javax.swing.JFrame {
    //Declarar un modelo para tabla
    DefaultTableModel ModeloTabla;
    
    //Declararvarables globales
    Empleado11 UnEmp;
    Empleado11[] ArregloEmp;
    
    //Encabezado de tabla
    String[] cabecera ={"N°","Código","Nombres","Area","Tipo Seg","Horas Extras",
    "Sueldo","Monto H.E","Monto Seguro","Monto Essalud", "Sueldo Neto"};
    //generando una matriz en blanco para los datos de la tabla
    String[][] data={};
    //Contador para contar la cantidad de elementos en el vecor
    int NumEmp;
    public NewJFrame11() {
        initComponents();
                initComponents();
        //generando un arreglo de 100 empleados
        ArregloEmp=new Empleado11[100];
        //generando el modelo para la tabla
        ModeloTabla=new DefaultTableModel(data,cabecera);
        //colocando el modelo sobre la tabla
        jTable1.setModel(ModeloTabla);
        //inicializando el contador en 0
        NumEmp=0;

    }
    void InsertarEnTabla(Empleado11 UnEmp){
        //dado formato para los datos numericos
        DecimalFormat df2= new DecimalFormat("####.00");
        //generando los datos con formato numerico
        String me=df2.format(UnEmp.montoHExtras());
        String ms=df2.format(UnEmp.montoSeguro());
        String mes=df2.format(UnEmp.montoEssalud());
        String sn=df2.format(UnEmp.sueldoNeto());
        //creando el arreglo de objetos para la tabla 
        Object [] fila={NumEmp+1,UnEmp.codigo,UnEmp.nombre,UnEmp.area,UnEmp.sueldoBase,UnEmp.horasExtras,
            UnEmp.tipo_seg,me,ms,mes,sn};
        // Agregando nuevos datos a la tabla 
        ModeloTabla.addRow(fila);
        }
    void LimpiarEntradas(){
        jTexCodigo.setText("");
        jTextNombre.setText("");
        jComboBoxSeguro.setSelectedIndex(0);
        jTextSueldoBase.setText("");
        jTextHorasExtra.setText("");
        jComboBoxArea.setSelectedIndex(0);
        jTexCodigo.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTexCodigo = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextSueldoBase = new javax.swing.JTextField();
        jTextHorasExtra = new javax.swing.JTextField();
        jComboBoxSeguro = new javax.swing.JComboBox<>();
        jComboBoxArea = new javax.swing.JComboBox<>();
        jButtonGrabar = new javax.swing.JButton();
        jButtonResumen = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTexCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));

        jTextNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        jTextSueldoBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Sueldo base"));

        jTextHorasExtra.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas extra"));

        jComboBoxSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AFP", "SNP" }));
        jComboBoxSeguro.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de seguro"));

        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marketing", "Sistemas" }));
        jComboBoxArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Área"));
        jComboBoxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAreaActionPerformed(evt);
            }
        });

        jButtonGrabar.setText("GRABAR");
        jButtonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGrabarActionPerformed(evt);
            }
        });

        jButtonResumen.setText("MOSTRAR RESUMEN");
        jButtonResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResumenActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº", "Código", "Nombres", "Área", "Seguro", "H.Extra", "Sueldo", "Monto H.E.", "Monto Seg", "M. Essalud", "Sueldo neto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("RESUMEN DE DATOS"));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Promedio de sueldos de Marketing"));
        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados con monto mayor a 100 soles"));
        jScrollPane4.setViewportView(jTextPane3);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados de Sistemas con monto por hora entre 500 a 800 soles"));
        jScrollPane5.setViewportView(jTextPane4);

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado del SNP con menor monto de descuento"));
        jScrollPane6.setViewportView(jTextPane5);

        jScrollPane7.setBorder(javax.swing.BorderFactory.createTitledBorder("Total de gastos de empresa en pagos a empleados"));
        jScrollPane7.setViewportView(jTextPane6);

        jScrollPane8.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado con mayor sueldo neto"));
        jScrollPane8.setViewportView(jTextPane7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTexCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextHorasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSeguro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxArea)
                    .addComponent(jButtonGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNombre)
                    .addComponent(jTexCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSeguro)
                    .addComponent(jButtonResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextSueldoBase)
                    .addComponent(jTextHorasExtra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGrabarActionPerformed
        //capturar la infomacion de los empleados de los obejtos del formulario
        String cod=jTexCodigo.getText();
        String nom=jTextNombre.getText();
        String seguro=jComboBoxSeguro.getSelectedItem().toString();
        double sueldo=Double.parseDouble(jTextSueldoBase.getText());
        int h_extras=Integer.parseInt(jTextHorasExtra.getText());
        String area=jComboBoxArea.getSelectedItem().toString();
        //crando empleado
        UnEmp =new Empleado11(cod,nom,area,sueldo,h_extras,seguro);
        //colocando el empleado en una posicion
        ArregloEmp[NumEmp]=UnEmp;
        //agregando un empleado a la tabla
        InsertarEnTabla(UnEmp);
        //incrementando el contador en 1
        NumEmp++;
        //Limpiando las entradas
        LimpiarEntradas();
    }//GEN-LAST:event_jButtonGrabarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        LimpiarEntradas();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResumenActionPerformed
        //declaracion de variables 
        String a="", e="";
        double b=0, c=0, ss=0, cont=0, d=0, f=0, mayor=-1, menor=9999999;
        //iniciando el proceso repetitivo para recorrer el vector
        for(int i=0;i<NumEmp;i++ )
        {// a) nombre del empleado que tenga el mayor sueldo neto
            if (ArregloEmp[i].sueldoNeto()> mayor)
            { mayor = ArregloEmp[i].sueldoNeto();
                a = ArregloEmp[i].nombre;
            }
            //b) promedio de sueldos netos del area de marketing
            if(ArregloEmp[i].area.equals("Marketing"))
            { ss=ss+ArregloEmp[i].sueldoNeto();
                cont++;
                b=ss/cont;
            }
            
            //c) numero de empleados cuyp monto de seguro superen ls 100 so
            if(ArregloEmp[i].montoSeguro()>100)
                c++;
            
            //d) numero de empleados del area de sistemas cuyo monto
            //   de horas extra estan entre 500 y 800 so
            if(ArregloEmp[i].area.equals("Sistemas")&& ArregloEmp[i].montoHExtras()>=500
                && ArregloEmp[i].montoHExtras()<=800)
            d++;
            
            //e) empleado snp cpn el menor onto de descuento
            if(ArregloEmp[i].tipo_seg.equals("SNP")&& ArregloEmp[i].montoDescuentos()<menor){
                menor = ArregloEmp[i].montoDescuentos();
                e = ArregloEmp[i].nombre;
            }
            
            //f) total de gastos de la empresa en pagar empleados
            f = f+ ArregloEmp[i].sueldoBruto();
        }
        
        //datos salida
        jTextPane2.setText(a);
        jTextPane3.setText(String.valueOf(b));
        jTextPane4.setText(String.valueOf(c));
        jTextPane5.setText(String.valueOf(d));
        jTextPane6.setText(e);
        jTextPane7.setText(String.valueOf(f));
    }//GEN-LAST:event_jButtonResumenActionPerformed

    private void jComboBoxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAreaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGrabar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonResumen;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxArea;
    private javax.swing.JComboBox<String> jComboBoxSeguro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTexCodigo;
    private javax.swing.JTextField jTextHorasExtra;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextField jTextSueldoBase;
    // End of variables declaration//GEN-END:variables
}
